import { Providers } from "../redux/providers/providers";
import { MODAL_LAYER_ID } from "../utils/constants";
import { Footer } from "./Layouts/Footer/Footer";
import { Header } from "./Layouts/Header/Header";
import { Wrapper } from "./components/containers/Wrapper/Wrapper";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ["cyrillic"] });

export const metadata = {
  title: "Билетопоиск",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Header />
          <Wrapper>{children}</Wrapper>
          <Footer />
          <div className={MODAL_LAYER_ID} id={MODAL_LAYER_ID} />
        </Providers>
      </body>
    </html>
  );
}
